FROM node:16

WORKDIR /usr/src/app

EXPOSE 5000

COPY package* .

RUN npm install

COPY . .

# build static files
RUN REACT_APP_BACKEND_URL=http://localhost:8080 npm run build

RUN npm install -g serve

ENV REACT_APP_BACKEND_URL="http://localhost:8080"

CMD ["serve", "-s", "-l", "5000", "build"]
