version: '3.8'

services:
  frontend:
    image: example-front
    build: ../../material-applications/example-frontend
    ports:
      - 5000:5000

  backend:
    image: example-back
    build: ../../material-applications/example-backend
    ports:
      - 8080:8080