version: '3.8'

services:
  frontend:
    image: example-front
    build: ../../material-applications/example-frontend
    #ports:
    #  - 5000
    networks:
      - dev

  backend:
    image: example-back
    build: ../../material-applications/example-backend
    environment:
      - REDIS_HOST=redis

      # The hostname for postgres database. (port will default to 5432 the default for Postgres)
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DATABASE=tietokanta
    depends_on:
      - redis
      - postgres
    #ports:
    #  - 8080
    networks:
      - dev

  redis:
    image: redis
    networks:
      - dev

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tietokanta
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
      - dev

  proxy:
    image: nginx
    volumes:
      # The way nginx and its modules work is determined in the configuration file
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    # Enable this for detailed routing debug info
    command: [nginx-debug, '-g', 'daemon off;']
    depends_on:
      - backend
    networks:
      - dev

networks:
  dev:
    driver: bridge
